# This file was generated by GoReleaser. DO NOT EDIT.
class Ecctl < Formula
  desc "Elastic Cloud Control, the official Elastic Cloud and ECE command line interface"
  homepage "https://github.com/elastic/ecctl"
  version "1.4.0"

  if OS.mac?
    url "https://download.elastic.co/downloads/ecctl/1.4.0/ecctl_1.4.0_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "20c41e2ab85f26d5243cc8d220484b40a6c301e863c072cbef7782c1cfe987ea"
  elsif OS.linux?
    url "https://download.elastic.co/downloads/ecctl/1.4.0/ecctl_1.4.0_linux_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "df3ee295f58be0f97aeeea08a262d1a6ab20bdd2029d38c2832a3a43da6f9597"
  end

  def install
    bin.install "ecctl"
    system "#{bin}/ecctl", "generate", "completions", "-l", "#{var}/ecctl.auto"
  end

  def caveats; <<~EOS
    To get autocompletions working make sure to run "source <(ecctl generate completions)".
    If you prefer to add to your shell interpreter configuration file run, for bash or zsh respectively:
    * `echo "source <(ecctl generate completions)" >> ~/.bash_profile`
    * `echo "source <(ecctl generate completions)" >> ~/.zshrc`.
  EOS
  end

  test do
    system "#{bin}/ecctl version"
  end
end
