# This file was generated by GoReleaser. DO NOT EDIT.
class Ecctl < Formula
  desc "Elastic Cloud Control, the official Elastic Cloud and ECE command line interface"
  homepage "https://github.com/elastic/ecctl"
  version "1.14.1"

  if OS.mac?
    url "https://download.elastic.co/downloads/ecctl/1.14.1/ecctl_1.14.1_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "bb97f851e80e9d4702669f2369aac5a7efc10a76f291f8b68f2d967f0cdcbb75"
  elsif OS.linux?
    url "https://download.elastic.co/downloads/ecctl/1.14.1/ecctl_1.14.1_linux_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "469dc36fb06c8d52926a41f6ee2ab8eb71424d70ef1a16b1cb87852f313dd807"
  end

  def install
    bin.install "ecctl"
    system "#{bin}/ecctl", "generate", "completions", "-l", "#{var}/ecctl.auto"
  end

  def caveats; <<~EOS
    To get autocompletions working make sure to run "source <(ecctl generate completions)".
    If you prefer to add to your shell interpreter configuration file run, for bash or zsh respectively:
    * `echo "source <(ecctl generate completions)" >> ~/.bash_profile`
    * `echo "source <(ecctl generate completions)" >> ~/.zshrc`.
  EOS
  end

  test do
    system "#{bin}/ecctl version"
  end
end
